// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/flutter_bspatch.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlutterBspatchBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterBspatchBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterBspatchBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// 应用 bspatch 补丁（文件路径方式）
  ///
  /// @param old_file    原始文件路径
  /// @param patch_file  补丁文件路径
  /// @param new_file    输出文件路径
  /// @return            0 表示成功，负数表示错误码
  int bspatch_apply(
    ffi.Pointer<ffi.Char> old_file,
    ffi.Pointer<ffi.Char> patch_file,
    ffi.Pointer<ffi.Char> new_file,
  ) {
    return _bspatch_apply(old_file, patch_file, new_file);
  }

  late final _bspatch_applyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bspatch_apply');
  late final _bspatch_apply = _bspatch_applyPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// 应用 bspatch 补丁（内存方式）
  ///
  /// @param old_data       原始数据指针
  /// @param old_size       原始数据大小
  /// @param patch_data     补丁数据指针
  /// @param patch_size     补丁数据大小
  /// @param new_data       输出数据指针（由调用者分配）
  /// @param new_size       输出数据大小（输入：缓冲区大小，输出：实际大小）
  /// @return               0 表示成功，负数表示错误码
  int bspatch_apply_bytes(
    ffi.Pointer<ffi.Uint8> old_data,
    int old_size,
    ffi.Pointer<ffi.Uint8> patch_data,
    int patch_size,
    ffi.Pointer<ffi.Uint8> new_data,
    ffi.Pointer<ffi.Int64> new_size,
  ) {
    return _bspatch_apply_bytes(
      old_data,
      old_size,
      patch_data,
      patch_size,
      new_data,
      new_size,
    );
  }

  late final _bspatch_apply_bytesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int64,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int64,
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<ffi.Int64>,
          )
        >
      >('bspatch_apply_bytes');
  late final _bspatch_apply_bytes = _bspatch_apply_bytesPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Int64>,
        )
      >();

  /// 从补丁文件获取新文件大小
  ///
  /// @param patch_data  补丁数据指针
  /// @param patch_size  补丁数据大小
  /// @return            新文件大小，负数表示错误
  int bspatch_new_size(ffi.Pointer<ffi.Uint8> patch_data, int patch_size) {
    return _bspatch_new_size(patch_data, patch_size);
  }

  late final _bspatch_new_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<ffi.Uint8>, ffi.Int64)
        >
      >('bspatch_new_size');
  late final _bspatch_new_size = _bspatch_new_sizePtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// 获取错误描述
  ///
  /// @param error_code  错误码
  /// @return            错误描述字符串
  ffi.Pointer<ffi.Char> bspatch_error_string(int error_code) {
    return _bspatch_error_string(error_code);
  }

  late final _bspatch_error_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'bspatch_error_string',
      );
  late final _bspatch_error_string = _bspatch_error_stringPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();
}

const int BSPATCH_SUCCESS = 0;

const int BSPATCH_ERROR_INVALID_PATCH = -1;

const int BSPATCH_ERROR_CORRUPT_PATCH = -2;

const int BSPATCH_ERROR_MEMORY = -3;

const int BSPATCH_ERROR_IO = -4;

const int BSPATCH_ERROR_SIZE_MISMATCH = -5;
